#define PEBBLE_ACCRETION_TESTPROBLEM 
#define BOX_SPATIAL_DIMENSION 2
#define BOX_SHEARING 2
#define EOS_GAMMA (1.001)
#define EOS_ENFORCE_ADIABAT (1.0)
#define BOX_PERIODIC 
#define HYDRO_MESHLESS_FINITE_MASS 
#define SELFGRAVITY_OFF 
#define GRAIN_FLUID 
#define GRAIN_BACKREACTION 
#define GRAIN_RDI_TESTPROBLEM 
#define SPAWN_PARTICLES_VIA_SPLITTING 
#define BOX_BND_PARTICLES 
#define BOX_SHEARING_Q (3./2.)
